Add checkOrganization API
pagopa/selfcare-ms-external-interceptor pull request #22
Opened 2023-08-25 13:13 UTC by KevinSi96

#### List of Changes

Add checkOrganization Api 

#### Motivation and Context

Some products needs to check if an organization has already onboarded the product prior to the onboarding process.
Two api's has been introduced, one to retrieve the product authentication token and one for organization onboarding status check on product side

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2023-08-29 15:33 UTC, manuraf requested changes

2023-08-29 15:33 UTC, manuraf commented on connector/rest/src/main/java/it/pagopa/selfcare/external_interceptor/connector/rest/interceptor/FDAuthorizationInterceptor.java
> +                .header(HttpHeaders.ACCEPT, "*/*");
RequestTemplate might be isolated from others requests...

2023-08-30 08:58 UTC, manuraf approved these changes

2023-08-30 09:26 UTC, gianmarcoplutino approved these changes

2023-08-30 09:29 UTC, merged